query CurrentProject($_id: String!) {
	currentProject(_id: $_id) {
        _id
        name
        description
    	updatedAt
        lists {
            _id
          	name
          	insertedAt
          	updatedAt
        }
        teams {
            _id
            roles {
                _id
                name
            }
            user {
                username
                _id
            }
        }
        owner {
            username
        }
    }
}