query projectListItemGetAll($projectListId: String){
    projectListItemGetAll(projectListId: $projectListId) {
        _id
        title
        description
        projectListId
        state
        availableHandler
        insertedAt
        developerId
        canEdit
        Developer {
            username
        },
        Priority {
            _id
            name
            order
        }
    }
}