mutation ($username: String!, $password: String!) {
    signup(username: $username, password: $password) {
        _id
        username
        token,
        insertedAt,
        insertedBy,
        isDeleted
    }
}